# Generated by Django 3.0.5 on 2021-11-17 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_auto_20211117_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={},
        ),
    ]
