# Generated by Django 3.0.5 on 2021-11-17 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_auto_20211117_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'entries'},
        ),
    ]
